name: Comment on new issues
on:
  issues:
    types: [opened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment on new issues
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for opening this issue 🎉

            Please do not start working on this issue or submit a pull request until a maintainer has assigned it to you. This helps us manage the workflow and avoid duplicate efforts.

            >We appreciate your understanding and cooperation.
